name: switchScript

on:
  workflow_dispatch:
  issue_comment:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
